# Generated by Django 2.0 on 2018-11-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=25, verbose_name='年龄'),
        ),
    ]
